services:
  api:
    image: esgapifase6-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=EsgComplianceDb;User Id=sa;Password=${SQL_SA_PASSWORD};Encrypt=False;TrustServerCertificate=True
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - appnet
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SA_PASSWORD}
    ports:
      - "1434:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - appnet

volumes:
  mssqldata:

networks:
  appnet:
