name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore "ESG API/ESG.Compliance.Api.sln"

      - name: Build (Release)
        run: dotnet build "ESG API/ESG.Compliance.Api.sln" -c Release --no-restore

      - name: Run BDD tests (Release)
        env:
          TEST_BASE_URL: http://localhost:8081
          DOTNET_ROLL_FORWARD: LatestMajor
        run: dotnet test "ESG API/ESG.Compliance.BddTests" -c Release --no-build --verbosity normal